import os, smtplib, mimetypes, glob
from email.message import EmailMessage
from pathlib import Path

SMTP_HOST = os.getenv("SMTP_HOST", "")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
REPORT_FROM = os.getenv("REPORT_FROM", "")
REPORT_TO = os.getenv("REPORT_TO", "")
REPORT_DIR = Path("report")

SUBJECT = "DevSecOps: Automated Security & Test Reports"
BODY_TEXT = """Hello Team,

Attached are the latest DevSecOps reports generated by Jenkins:
• Bandit (SAST)
• Dependency Vulnerabilities
• Trivy (Container scan)
• ZAP (DAST)
• Consolidated HTML and PDF
• Version tracking

Regards,
Jenkins – DevSecOps Automation
"""

PATTERNS = [
    "bandit_report.html","dependency_vuln.txt","report.html",
    "test_result_report_v*.html","trivy_report.txt",
    "version.txt","zap_dast_report.html","test_result_report_v*.pdf"
]

def attach_files(msg, base_dir, patterns):
    found = False
    for pattern in patterns:
        for path in glob.glob(str(base_dir / pattern)):
            fp = Path(path)
            if fp.is_file():
                ctype, _ = mimetypes.guess_type(fp.name)
                if not ctype: ctype = "application/octet-stream"
                maintype, subtype = ctype.split("/", 1)
                with open(fp, "rb") as f:
                    msg.add_attachment(f.read(), maintype=maintype, subtype=subtype, filename=fp.name)
                print(f"📎 Attached: {fp.name}")
                found = True
    if not found:
        print("⚠️ No matching artifacts to attach.")
    return found

def main():
    recipients = [x.strip() for x in REPORT_TO.split(",") if x.strip()]
    msg = EmailMessage()
    msg["From"] = REPORT_FROM
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = SUBJECT
    msg.set_content(BODY_TEXT)
    attach_files(msg, REPORT_DIR, PATTERNS)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)
        print("✅ Email sent successfully.")

if __name__ == "__main__":
    main()
